# 
#  					BukkitDev Help page : http://dev.bukkit.org/server-mods/mycommand/  					#
LISTENERS:
  CUSTOM_COMMANDS_GAME: true
  CUSTOM_COMMANDS_CONSOLE: true
  BLOCK_LISTENER: true
  ITEM_LISTENER: true
  SIGN_LISTENER: true
  VEHICLE_LISTENER: true
  MOVE_LISTENER: true
  EXTRA_LISTENER: true
  PLUGIN_MESSAGE_LISTENER: true
  NPCS_LISTENER: false
  CHAT_LISTENER: false
DEBUG:
  GAME: false
  CONSOLE: true
  DISABLE_PERMISSIONS: false
  USE_UUID_FOR_PLAYERDATA: true
  USE_NAME_INSTEAD_OF_ID_IN_THE_PERMISSION_NAME: true
  USE_THE_UPDATER: true
ECONOMY:
  ALLOW_DEBIT: false
SCHEDULER:
  ENABLED: false
  DATE_FORMAT: d M yyyy
  FIRST_CHECK_AFTER_SEC: 60
  LAUNCH_CHECK_ON_EVERY_N_MIN: 60
SIGNS:
  HEADER: '[JeriCraft]'
  DELAY_SEC: 5
BLOCKS:
  MATERIAL:
    RIGHT_CLICK_INTERACTION:
    - LEVER
    - GRASS_BLOCK
    - STONE_BUTTON
    - WOOD_BUTTON
    - WOODEN_DOOR
    - STONE_PLATE
    - WOOD_PLATE
    - IRON_PLATE
    - SIGN
    - SIGNS
    PHYSICAL_INTERACTION:
    - STONE_PLATE
    - WOOD_PLATE
    - IRON_PLATE
    - LEVER
    - GRASS_BLOCK
    - STONE_BUTTON
    - WOOD_BUTTON
    - WOODEN_DOOR
    - STONE_PLATE
    - WOOD_PLATE
    - IRON_PLATE
    - DETECTOR_RAIL
    - SIGN
    - SIGNS
COMMANDS:
  MAX_ARGUMENTS: 20
NPCS:
  DELAY_SEC: 5
