# I---------------------------I
# I Admin Chat Channel Config I
# I---------------------------I

# I---------------------------I
# I    Config version 0.9     I
# I---------------------------I

Version: "0.9"

# --- Color / Formatting codes ---

# &0 black
# &1 dark blue
# &2 dark green
# &3 dark aqua
# &4 dark red
# &5 dark purple
# &6 gold
# &7 gray
# &8 dark gray
# &9 blue
# &a green
# &b aqua
# &c red
# &d light purple
# &e yellow
# &f white

# &k obfuscated
# &l bold
# &m strikethrough
# &n underline
# &o italic
# &r reset

# --- Chat format options ---

# %MSG% = The message the player sends.
# %NAME% = The players name.
# %PREFIX% = The users prefix. This only works if you have PEX (PermissionsEx) or GroupManager. If you dont have any of them so dont use %PREFIX%.
# %SUFFIX% = The users suffix. This only works if you have PEX (PermissionsEx) or GroupManager. If you dont have any of them so dont use %SUFFIX%.
# %DISNAME% = The players display name. This will make the rank prefix/nick be in the user name.
# NOTE: %DISNAME% will get the players prefix/suffix if there is any and essentialsChat/any other chat plugins that allows prefix/suffixes is on the server.
# Ex 1: 'AdminFormat: "[AC] %DISNAME% : %MSG%"' will be: [AC] [Owner]RealName : Hello there!.
# Ex 2: 'AdminFormat: "[AC] %DISNAME% : %MSG%"' will be: [AC] [Owner]NickName : Hello there!.
# Ex 3: 'AdminFormat: "[AC] %NAME% : %MSG%"' will be: [AC] RealName : Hello there!.
# Ex 4: 'AdminFormat: "[AC] %PREFIX% %DISNAME% : %MSG%"' will be: [AC] [Owner] [Owner]NickName : Hello there!.
# Ex 4: 'AdminFormat: "[AC] %PREFIX% %NAME% : %MSG%"' will be: [AC] [Owner] RealName : Hello there!.

# The %DISNAME% Should work with pex prefixes/sufixes, essentials nicks, groupmanager prefixes/sufixes and more.

#----------------------------

# --- Admin Channel ---

# AdminFormat - The format the admin chat will use.
AdminFormat: "&8[&4&lAdmin-Chat&8] &r%NAME%&8: &c%MSG%"

# --- Mod Channel ---

# ModFormat - The format the mod chat will use.
ModFormat: "&8[&9&lMod-Chat&8] &r%NAME%&8: &b%MSG%"

# --- Helper Channel ---

# HelperFormat - The format the helper chat will use.
HelperFormat: "&7[&cMCC&7]&f: &8%NAME%&f &c%MSG%"

# --- Staff Channel ---

# StaffFormat - The format the staff chat will use.
StaffFormat: "&8[&6&lStaff-Chat&8] &r%NAME%&8: &e%MSG%"

# --- CommandBlock / Console ---

# Note : CommandBlockName and ConsoleName will replace %DISNAME% AND %NAME%!

# CommandBlockName - The name that will show in chat when a command block uses the chat.
CommandBlockName: ""

# ConsoleName - The name that will show in the chat when console uses the chat.
ConsoleName: ""