#
# WorldEdit's configuration file
#
# About editing this file:
# - DO NOT USE TABS. You MUST use spaces or Bukkit will complain. If
#   you use an editor like Notepad++ (recommended for Windows users), you
#   must configure it to "replace tabs with spaces." In Notepad++, this can
#   be changed in Settings > Preferences > Language Menu.
# - Don't get rid of the indents. They are indented so some entries are
#   in categories (like "max-blocks-changed" is in the "limits"
#   category.
# - If you want to check the format of this file before putting it
#   into WorldEdit, paste it into http://yaml-online-parser.appspot.com/
#   and see if it gives "ERROR:".
# - Lines starting with # are commentsand so they are ignored.
#

limits:
    allow-extra-data-values: true
    max-blocks-changed:
        default: -1
        maximum: -1
    max-polygonal-points:
        default: -1
        maximum: 1000
    max-radius: -1
    max-super-pickaxe-size: 100
    max-brush-radius: 100
    butcher-radius:
        default: -1
        maximum: -1
    disallowed-blocks: []

use-inventory:
    enable: false
    allow-override: true
    creative-mode-overrides: false

logging:
    log-commands: true
    file: worldedit.log

super-pickaxe:
    drop-items: false
    many-drop-items: false

snapshots:
    directory:

navigation-wand:
    item: 345
    max-distance: 100

scripting:
    timeout: 3000
    dir: craftscripts

saving:
    dir: schematics

files:
    allow-symbolic-links: false

history:
    size: 30
    expiration: 15

wand-item: 271
shell-save-type:
no-double-slash: false
no-op-permissions: true
debug: false
show-help-on-first-use: false
