# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    host: 203.57.45.63
    port: 3306
    name: Chalwk
    user: Chalwk
    password: hHM8dFpbaSGwhyKn
    maxConnections: 100
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
  global:
    enabled: false
    host: 203.57.45.63
    port: 3306
    name: Chalwk
    user: Chalwk
    password: hHM8dFpbaSGwhyKn
    maxConnections: 100
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
  convert:
    enabled: false
    host: 127.0.0.1
    port: 3306
    name: local_bans
    user: root
    password: ''
    maxConnections: 10
    tables:
      bansTable: bm_bans
      bansRecordTable: bm_ban_records
      ipBansTable: bm_ip_bans
      ipBansRecordTable: bm_ip_records
      kicksTable: bm_kicks
      mutesTable: bm_mutes
      mutesRecordTable: bm_mutes_records
      playerIpsTable: bm_player_ips
      warningsTable: bm_warnings
mutedCommandBlacklist:
- msg
- w
- r
- mail
- m
- t
- whisper
- emsg
- tell
- er
- reply
- ereply
- email
- action
- describe
- eme
- eaction
- edescribe
- etell
- ewhisper
- pm
softMutedCommandBlacklist:
- msg
- w
- r
- mail
- m
- t
- whisper
- emsg
- tell
- er
- reply
- ereply
- email
- action
- describe
- eme
- eaction
- edescribe
- etell
- ewhisper
- pm
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: true
logIps: true
displayNotifications: true
broadcastOnSync: true
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
  actions:
    '10':
    - cmd: ban [player] [reason]
      delay: 10
    - cmd: mute [player] [reason]
warningMute: false
hooks:
  enabled: true
checkForUpdates: true
offlineAutoComplete: true
punishAlts: true
denyAlts: false
cleanUp:
  kicks: 0
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
checkOnJoin: true
createNoteReasons: true
onlineMode: true
