##############
# WORLD INFO #
##############
random_world: false

valid_worlds:
  - world

radius:
  max_X: 30000
  max_Z: 30000
  min_X: 0
  min_Z: 0
  
######################
# PRICE AND COOLDOWN #
######################
price: 0

cooldown: 30
 
portal:
  price: false
  cooldown: true
sign:
  price: false
  cooldown: true
self:
  price: false
  cooldown: true
cmd:
  price: false
  cooldown: true
  
##############
# BLACK LIST #
##############
biomes:
  - OCEAN
  - RIVER
  - DEEP_OCEAN
blocks:
  - CACTUS
  - WATER
  - LAVA
 
######################
# PLUGIN INTEGRATION #
######################
towny: false
factions: false
worldguard: true
worldborder: false

########
# MISC #
########
debug: true
send_message_on_tp: true
anticheat: true
preventPortalUpdate: true