armor: true
debug: false
dont_spam_chat: false
enderchest: false
no_drops: true
no_falling_drops: true
no_pickups: true
remove_potions: true
restrict_creative: true
save_on_death: true
survival_on_world_change: false
xp: true
track_creative_place:
  enabled: false
  break_no_drop: false
  no_piston_move: false
  attached_block: false
  worlds:
  - world
  dont_track:
  - NOT_USED
  dont_track_is_whitelist: false
creative_blacklist: true
blacklist:
- TNT
- BEDROCK
break_bedrock: false
command_blacklist: true
commands:
- ec*
- ec
- /customec open*
- /customec open
- customec open*
- customec open
- customec*
- customec
- sf*
- give
- i
- buy
- esell
- sell
- sell*
- sell hand
- sell all
- sf guide
- sf
- fix
- efix
- repair
- fix hand
- efix hand
- erepair
- erepair hand
custom_attributes: false
restrict_spectator: true
bypass:
  inventories: true
  items: true
  blacklist: true
  survival: true
  commands: true
uuid_conversion_done: true
blocks_conversion_done: true
storage:
  mysql:
    server: 203.57.45.63
    port: 3306
    database: Chalwk
    user: Chalwk
    password: hHM8dFpbaSGwhyKn
    pool_size: 10
    test_connection: false
  database: MySQL
debug_level: ERROR
